import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.Scanner;


public class FileIOExample {


    public static void main(String[] args) {
        String currentDir = System.getProperty("user.dr");
        System.out.println("urrent directory: " + currentDir);

        Path inputPath = Path.of("input.txt");
        Path outputPath = Path.of("output.txt");

        try (PrintWriter writer = new PrintWriter(outputPath.toString(), StandardCharsets.UTF_8)) {
            writer.println("This is a sample text file.");
            writer.println("It contains multiple lines.");
            writer.printf("Generated by %s.%n", "FileIOExample");
        }
        System.out.println(("Data written to " + outputPath);

        try(Scanner scanner = new Scanner(inputPath, StandardCharsets.UTF_8)) {
            System.out.println("\nReading data from " + inputPath + ":");

            while(scanner.hasNextLine()) {
                String line = scanner.nextLine();
                System.out.println(line);
            }
        } catch (IOException e) {
            System.out.println(("Error reading from file: " + e.getMessage());
        }

        String sample

    }
}
